## 01. 텐서 초기화
- 초기화 : 텐서에 특정 값을 채워서 생성하는 것

In [3]:
import torch
import numpy as np

# pytorch 버전 확인
torch.__version__

'2.5.1'

### 1-1. 초기화 되지 않은 Tensor
- 특정한 값이 채워지지 않은 상태로 생성하는 것

In [4]:
tensor = torch.empty(4, 2)
print(tensor)

tensor([[-2.5530e+38,  2.0809e-42],
        [ 0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00]])


### 1-2. 상수로 초기화된 Tensor
- ' torch.zeros() '
- ' torch.ones '

In [9]:
a = torch.ones(3,4, dtype = torch.long) # dtype으로 데이터 타입을 지정하 수 있다.
b = torch.zeros(2,2)
print(a)
print(b)

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])
tensor([[0., 0.],
        [0., 0.]])


### 1-3. 무작위하게 초기화된 Tensor
- ' torch.rand ' : 0~1 사이의 값으로 무작위로 초기화
- ' torch.randn ' : 표준정규분포에서 무작위로 초기화

In [13]:
a = torch.rand(3,3)
b = torch.randn(3,3)
print(a,b)

tensor([[0.3608, 0.0265, 0.8923],
        [0.2300, 0.2533, 0.4247],
        [0.3179, 0.8350, 0.6486]]) tensor([[ 0.3992,  1.0497, -1.2801],
        [ 1.7578, -0.8634,  1.8700],
        [ 0.7134,  0.0763,  1.2053]])


### 1-4. 직접 입력한 값으로 초기화

In [14]:
a = torch.tensor([1, 2.3])
a

tensor([1.0000, 2.3000])

### 1-5. Numpy 배열로부터 초기화

In [24]:
nd_arr = np.array([1, 2, 3])
a = torch.from_numpy(nd_arr)

# numpy array로 변환
b = torch.tensor([1,2,3])
new_nd = b.numpy()

type(new_nd)

numpy.ndarray

In [26]:
nd_arr = np.array([1, 2, 3])
a = torch.from_numpy(nd_arr)

# numpy array로 변환
b = torch.tensor([1,2,3,4,5])
new_nd = b.numpy()
new_nd[2] = 100

print(new_nd)
print(b)

[  1   2 100   4   5]
tensor([  1,   2, 100,   4,   5])


### 1-6. 특정 텐서와 같은 사이즈, 무작위로 값을 채움

In [21]:
a = torch.ones(3,4, dtype = torch.long) 
b = torch.zeros_like(a, dtype = torch.float)
b

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

### 1-7. 텐서의 속성

In [5]:
tensor = torch.rand(3,4, dtype=torch.float64)
print(tensor.size()) # 사이즈
print(tensor.shape) # 사이즈
print(tensor.dtype) # 데이터 타입
print(tensor.device) # 디바이스

torch.Size([3, 4])
torch.Size([3, 4])
torch.float64
cpu


### 1-8. 특정 타입의 텐서 생성

In [13]:
tensor = torch.rand(3,4, dtype=torch.float64)

new_tensor = torch.FloatTensor([1,2,3])
new_tensor.dtype

int_tensor = torch.IntTensor([1,2,3])
int_tensor.dtype

torch.int32

In [14]:
tensor = torch.rand(3,4, dtype=torch.float64)

new_tensor = torch.FloatTensor([1,2,3])
print(new_tensor.dtype)

int_tensor = torch.IntTensor([1.1,2.1,3.1])
print(int_tensor.dtype)

torch.float32
torch.int32


### 1-9. 데이터 타입 캐스팅

In [15]:
float_tensor = torch.FloatTensor([1,2,3])
print(float_tensor.int())

int_tensor = torch.IntTensor([1.1,2.1,3.1])
print(int_tensor.float())

tensor([1, 2, 3], dtype=torch.int32)
tensor([1., 2., 3.])


### 1-10. CUDA Tensor

In [19]:
tensor = torch.rand(3,4, dtype=torch.float64)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

tensor = tensor.to(device)
tensor.device

device(type='cuda', index=0)

### 1-11. 다차원 Tensor 표현

#### 1-11-1. 0D Tensor(Scalar)
- 하나의 값을 담고 있는 텐서

In [23]:
t0 = torch.tensor(100)
print(t0.ndim)
print(t0.shape)
print(t0)

0
torch.Size([])
tensor(100)


#### 1-11-2. 1D Tensor(Vector)
- 값들을 저장하고 있는 리스트와 유사한 텐서

In [24]:
t1 = torch.tensor([1,2,3])
print(t1.ndim)
print(t1.shape)
print(t1)

1
torch.Size([3])
tensor([1, 2, 3])


#### 1-11-3. 2D Tensor(Matrix)
- 행렬과 같은 모양으로 두개의 축이 존재

In [ ]:
t2 = torch.tensor([[1,2,3],[4,5,6]])
print(t2.ndim)
print(t2.shape)
print(t2)

#### 1-11-3. 3D Tensor(Cube)
- 큐브와 같은 형태로 세 개의 축이 존재

In [26]:
t3 = torch.tensor([[[1,2,3],[4,5,6], [7,8,9]],
                    [[1,2,3],[4,5,6], [7,8,9]],    
                    [[1,2,3],[4,5,6], [7,8,9]]])
print(t3.ndim)
print(t3.shape)
print(t3)

3
torch.Size([3, 3, 3])
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])


#### 1-11-4. 4D Tensor
- 4개의 축

In [29]:
t4 = torch.rand(2,3,4,5)
t4

tensor([[[[0.2808, 0.0581, 0.2760, 0.5110, 0.4235],
          [0.4657, 0.1686, 0.1997, 0.2325, 0.9062],
          [0.5180, 0.4762, 0.4724, 0.1336, 0.8375],
          [0.3562, 0.1991, 0.7776, 0.8742, 0.1258]],

         [[0.0917, 0.5499, 0.2960, 0.0514, 0.0253],
          [0.8945, 0.8464, 0.2661, 0.0240, 0.2402],
          [0.3412, 0.1044, 0.6208, 0.9690, 0.0577],
          [0.4781, 0.2349, 0.8576, 0.9903, 0.6114]],

         [[0.3020, 0.4271, 0.7027, 0.1628, 0.1960],
          [0.9405, 0.5170, 0.7809, 0.4762, 0.9100],
          [0.9587, 0.2464, 0.7410, 0.6530, 0.5977],
          [0.2874, 0.0548, 0.3313, 0.1304, 0.4119]]],


        [[[0.8594, 0.6025, 0.4757, 0.7333, 0.8824],
          [0.5760, 0.0862, 0.6836, 0.8643, 0.1928],
          [0.1150, 0.3962, 0.4746, 0.4705, 0.9228],
          [0.7683, 0.2111, 0.0703, 0.1829, 0.0657]],

         [[0.8619, 0.1726, 0.5005, 0.2880, 0.2260],
          [0.2102, 0.5553, 0.3671, 0.0529, 0.8316],
          [0.2565, 0.6789, 0.9618, 0.6695, 0.3536],
  