## 02. 텐서의 연산

In [1]:
import torch

### 2-1. 산술 연산

In [4]:
tensor = torch.rand(2,2)
print(tensor)

tensor = tensor * 2
print(tensor)

tensor = tensor + 1
print(tensor)

tensor([[0.6506, 0.9281],
        [0.5726, 0.4979]])
tensor([[1.3013, 1.8562],
        [1.1452, 0.9959]])
tensor([[2.3013, 2.8562],
        [2.1452, 1.9959]])


In [ ]:
# 더하기
x = torch.rand(2,2)
y = torch.rand(2,2)
add = torch.add(x,y)
print(x, y)
print(x+y)
print(add)

# in-place 바꿔치기 연산
add = torch.add(x)
print(add)
y.add_(x)
print(y)    

tensor([[0.9349, 0.7672],
        [0.4171, 0.7180]]) tensor([[0.2591, 0.6562],
        [0.9222, 0.5638]])
tensor([[1.1940, 1.4234],
        [1.3393, 1.2818]])
tensor([[1.1940, 1.4234],
        [1.3393, 1.2818]])


In [7]:
# 빼기
x = torch.rand(2,2)
y = torch.rand(2,2)
sub = torch.sub(x,y)
print(x-y)
print(sub)

tensor([[ 0.0726,  0.2121],
        [ 0.1356, -0.1724]])
tensor([[ 0.0726,  0.2121],
        [ 0.1356, -0.1724]])


In [9]:
# 곱하기
x = torch.rand(2,2)
y = torch.rand(2,2)
mul = torch.mul(x,y)
print(x*y)
print(mul)

tensor([[0.4897, 0.4615],
        [0.4303, 0.6742]])
tensor([[0.4897, 0.4615],
        [0.4303, 0.6742]])


In [8]:
# 나누기
x = torch.rand(2,2)
y = torch.rand(2,2)
div = torch.div(x,y)
print(x/y)
print(div)

tensor([[0.1665, 0.6895],
        [0.7111, 1.0658]])
tensor([[0.1665, 0.6895],
        [0.7111, 1.0658]])


### 2-2. 각종 연산

In [11]:
a = torch.tensor(-10)
print("절대값 :", torch.abs(a))

b = torch.tensor(-3.3)
print("올림 :", torch.ceil(b)) # ceil : 올림
print("반올림 :", torch.round(b)) # round : 반올림
print("내림 :", torch.floor(b)) # floor : 내림

c = torch.randn(2,2)
print("클램프 :", torch.clamp(c, -0.5, 0.5)) # 0.5 값을 초과하는 건 다 0.5 값으로 맞춰주는 것, -0.5도 마찬가지
d = torch.tensor([[0.8, 0.3], [0.7,0.5]])
print("클램프 :", torch.clamp(c, -0.5, 0.5))

절대값 : tensor(10)
올림 : tensor(-3.)
반올림 : tensor(-3.)
내림 : tensor(-4.)
클램프 : tensor([[ 0.3035, -0.5000],
        [ 0.1474, -0.5000]])
클램프 : tensor([[ 0.3035, -0.5000],
        [ 0.1474, -0.5000]])


In [12]:
x= torch.randn(2,2)
y = torch.tensor([[1,2],[3,4]])
print("최솟값: ", torch.max(x))
print("최대값: ", torch.mean(x))
print("평균: ", torch.std(x))
print("표준편차: ", torch.sum(x)) 
print("\n")
print("모든 원소의 합: ", torch.sum(y, dim=0)) # dimension : 같은 인덱스끼리만 더하기
print("모든 원소의 곱: ", torch.prod(y))
print("중복된 값 제거: ", torch.unique(torch.tensor([1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 4]))) 


최솟값:  tensor(0.5000)
최대값:  tensor(-0.2104)
평균:  tensor(0.8341)
표준편차:  tensor(-0.8417)


모든 원소의 합:  tensor([4, 6])
모든 원소의 곱:  tensor(24)
중복된 값 제거:  tensor([1, 2, 3, 4])


### 2-3. 내적(dot product)

In [13]:
x = torch.tensor([[1,2],    
                  [3,4]])
y = torch.tensor([[5,6],    
                  [7,8]])

result = torch.matmul(x,y) # 행렬의 연산
print(result)

tensor([[19, 22],
        [43, 50]])
