## 03.Tensor의 조작

### 3-4. 인덱싱, 슬라이싱
- numpy처럼 활용

In [1]:
import torch

In [14]:
tensor = torch.tensor([[1,2],[3,4]])

# 1 불러오기
print(tensor[0,0]) 
# 1,2 불러오기
print(tensor[0,:]) 

a = torch.tensor([1,2,3,4,5])

# 뒤에서 2개 불러오기
print(a[-2:])

b = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
# 조건부로 불러오기
c = b[b > 3]
d = b[b % 2 == 0]
# 배열에 값을 넣어 인덱싱 할 수 도있음
e = b[[0,1],[1,2]]
e


tensor(1)
tensor([1, 2])
tensor([4, 5])


tensor([2, 6])

### 3-2. 텐서의 크기, 모양 변경

In [15]:
t = torch.rand(4,5)
print(t)

x = t.view(5,4)
print(x)

y = t.view(10,-1)
print(y)

tensor([[0.6534, 0.3283, 0.9283, 0.7074, 0.0874],
        [0.8731, 0.8349, 0.1404, 0.2478, 0.5689],
        [0.5329, 0.7973, 0.0921, 0.0440, 0.1745],
        [0.8404, 0.6732, 0.3460, 0.6596, 0.4200]])
tensor([[0.6534, 0.3283, 0.9283, 0.7074],
        [0.0874, 0.8731, 0.8349, 0.1404],
        [0.2478, 0.5689, 0.5329, 0.7973],
        [0.0921, 0.0440, 0.1745, 0.8404],
        [0.6732, 0.3460, 0.6596, 0.4200]])
tensor([[0.6534, 0.3283],
        [0.9283, 0.7074],
        [0.0874, 0.8731],
        [0.8349, 0.1404],
        [0.2478, 0.5689],
        [0.5329, 0.7973],
        [0.0921, 0.0440],
        [0.1745, 0.8404],
        [0.6732, 0.3460],
        [0.6596, 0.4200]])


### 3-3. Tensor의 숫자 얻기

In [16]:
x = torch.tensor(10)
print(x.item())

y = torch.rand(1)
print(y)
print(y.item())

10
tensor([0.0144])
0.014395475387573242


### 3-4. 차원 축소와 증가

#### 3-4-1. 차원 축소
- ' torch.squeeze() ' : 크기가 1인 차원을 축소함 

In [17]:
t = torch.rand(1,2,3)
print(t)
print(t.shape)

ts = torch.squeeze(t)
print(ts)
print(ts.shape)


tensor([[[0.9888, 0.7386, 0.0171],
         [0.9166, 0.9226, 0.3475]]])
torch.Size([1, 2, 3])
tensor([[0.9888, 0.7386, 0.0171],
        [0.9166, 0.9226, 0.3475]])
torch.Size([2, 3])


#### 3-4-2. 차원 증가(생성)
- 'torch.unsqueeze()': 지정한 위치에 새로운 차원을 생성

In [22]:
t = torch.rand(3,3,3)
print(t)
print(t.shape)

ts = torch.unsqueeze(t,0)
print(ts)
print(ts.shape)


tensor([[[0.6768, 0.8224, 0.4707],
         [0.5548, 0.7149, 0.3330],
         [0.7708, 0.7036, 0.2263]],

        [[0.8952, 0.2965, 0.7786],
         [0.9183, 0.0995, 0.0646],
         [0.8562, 0.3367, 0.5451]],

        [[0.9782, 0.0339, 0.9627],
         [0.3415, 0.8067, 0.1165],
         [0.0320, 0.8144, 0.4789]]])
torch.Size([3, 3, 3])
tensor([[[[0.6768, 0.8224, 0.4707],
          [0.5548, 0.7149, 0.3330],
          [0.7708, 0.7036, 0.2263]],

         [[0.8952, 0.2965, 0.7786],
          [0.9183, 0.0995, 0.0646],
          [0.8562, 0.3367, 0.5451]],

         [[0.9782, 0.0339, 0.9627],
          [0.3415, 0.8067, 0.1165],
          [0.0320, 0.8144, 0.4789]]]])
torch.Size([1, 3, 3, 3])


### 3-5. 텐서간 결합
- 'torch.stack()' : 동일한 형식의 텐서를 새롭게 그룹화함

In [24]:
x = torch.tensor([[1,2],[3,4]])
y = torch.tensor([[5,6],[7,8]])
z = torch.stack([x,y])
print(z)
print(z.shape)


tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
torch.Size([2, 2, 2])


- 'torch.cat()': 하나의 텐서로 병합
    - 새로운 차원 생성x

In [31]:
x = torch.tensor([[1,2],[3,4]])
y = torch.tensor([[5,6],[7,8]])
z = torch.cat((x,y), dim = 0) # dim = 1 로 하면 2행으로 합쳐진다.
print(z) # 열의 갯수는 맞아야하지만 행의 원소의 갯수는 달라도 된다.

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])


### 3-6. 텐서 나누기
- ' torch.chunk() '
    - 텐서를 몇개로 나눌지 지정
    - 나누어 떨어지지 않으면 마지막 조각은 크기가 다를 수 있음

In [41]:
# 기본 형태
t = torch.rand(5,3)
print(t) 

a,b,c = torch.chunk(t, 3, dim = 0)
print(a)
print(b)
print(c)

# 나누어 떨어지지 않아 마지막 조각의 크기가 다른 경우
t_1 = torch.rand(5,3)
print(t) 

a_1,b_1,c_1 = torch.chunk(t_1, 3, dim = 0)
print(a_1)
print(b_1)
print(c_1)


tensor([[0.3233, 0.5659, 0.8566],
        [0.9760, 0.2221, 0.1033],
        [0.8389, 0.9048, 0.2139],
        [0.4742, 0.8267, 0.4229],
        [0.9190, 0.9018, 0.8050]])
tensor([[0.3233, 0.5659, 0.8566],
        [0.9760, 0.2221, 0.1033]])
tensor([[0.8389, 0.9048, 0.2139],
        [0.4742, 0.8267, 0.4229]])
tensor([[0.9190, 0.9018, 0.8050]])
tensor([[0.0194, 0.9902, 0.0434],
        [0.9355, 0.7568, 0.1175],
        [0.1456, 0.5930, 0.1632],
        [0.1791, 0.4370, 0.4595],
        [0.7364, 0.2124, 0.0998]])
tensor([[0.0194, 0.9902, 0.0434],
        [0.9355, 0.7568, 0.1175]])
tensor([[0.1456, 0.5930, 0.1632],
        [0.1791, 0.4370, 0.4595]])
tensor([[0.7364, 0.2124, 0.0998]])


- ' torch.split() ': 텐서의 크기를 기준으로 나눔 

In [47]:
# 기본
t = torch.rand(6,3)
print(t)

x, y = torch.split(t, 3, dim=0)
print(x)
print(y)

tensor([[0.1653, 0.1525, 0.6603],
        [0.7076, 0.0174, 0.6221],
        [0.4387, 0.8817, 0.5313],
        [0.4451, 0.4934, 0.0479],
        [0.1103, 0.1674, 0.1500],
        [0.4324, 0.4915, 0.0149]])
tensor([[0.1653, 0.1525, 0.6603],
        [0.7076, 0.0174, 0.6221],
        [0.4387, 0.8817, 0.5313]])
tensor([[0.4451, 0.4934, 0.0479],
        [0.1103, 0.1674, 0.1500],
        [0.4324, 0.4915, 0.0149]])


In [51]:
# 배열 형태로 쪼개기도 가능
t = torch.tensor([1,2,3,4,5])
print(t)

x, y, z = torch.split(t, [2,2,1], dim=0)
print(x)
print(y)
print(z)

tensor([1, 2, 3, 4, 5])
tensor([1, 2])
tensor([3, 4])
tensor([5])
