## PyTorch Quiz 1 : Tensor 초기화

### 1. 빈 Tensor 생성하기
다음 조건에 맞는 Tensor를 생성하세요.
- 3x4 크기의 Tensor
- 값이 초기화되지 않은 상태

In [2]:
import torch
import numpy as np

tensor = torch.empty( 3, 4)
print(tensor)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


### 2. 0으로 채워진 Tensor 생성하기
다음과 같은 Tensor를 생성하세요.
- 2x5x3 크기의 Tensor
- 데이터 타입은 float64

In [3]:
tensor = torch.zeros(2,5,3, dtype= torch.float64)
print(tensor)

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]], dtype=torch.float64)


### 3. 1로 채워진 Tensor 생성하기
다음 조건에 맞는 Tensor를 생성하세요.
- 4x4 크기의 Tensor
- 데이터 타입은 int

In [5]:
tensor = torch.ones(4,4, dtype = torch.int) # int : int32, long : int64
print(tensor)

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)


### 4. 랜덤 값으로 채워진 Tensor 생성하기
다음 조건에 맞는 Tensor를 생성하세요.
- 3x3 크기의 Tensor
- 모든 값이 0과 1 사이의 랜덤 값

In [6]:
tensor = torch.rand(3,3)
print(tensor)

tensor([[0.4875, 0.9447, 0.7628],
        [0.3073, 0.6142, 0.6079],
        [0.8036, 0.2645, 0.3233]])


### 5. 다차원 Tensor 생성하기
다음과 같은 다차원 Tensor를 생성하세요.
- 값이 다음과 같은 2x3의 2D 배열
    ```
    [[1, 2, 3],
     [4, 5, 6]]
    ```

In [7]:
tensor = torch.tensor([[1, 2, 3],[4, 5, 6]])
tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

### 6. Tensor의 값을 변경하기
1. 표준정규분포의 값을 랜덤으로 갖는 2x2 Tensor를 생성하세요.
2. 생성된 Tensor의 값을 모두 0으로 바꿔보세요. 

In [14]:
tensor = torch.randn(2,2)
print(tensor)

# 0으로 바꾸기
result = torch.zeros_like(tensor)
print(result)

tensor([[-0.9014, -0.2163],
        [-1.9221,  0.1151]])
tensor([[0., 0.],
        [0., 0.]])
