In [1]:
import torch

## PyTorch Quiz 2 : 연산

### 1. 덧셈과 뺄셈 연습
1. [2, 4, 6]으로 초기화된 1D Tensor를 생성하세요.
2. 각 요소에 5를 더한 Tensor를 출력하세요.
3. 각 요소에서 3을 뺀 Tensor를 출력하세요.


In [3]:
# 여기에 코드를 작성합니다
answer_1 = torch.tensor([2,4,6])
print(answer_1)
answer_2 = answer_1 + 5
print(answer_2)
answer_3 = answer_1 - 3
print(answer_3)

tensor([2, 4, 6])
tensor([ 7,  9, 11])
tensor([-1,  1,  3])


### 2. Tensor 간의 연산
1. 3x3 크기의 Tensor 2개를 생성하세요.
2. 두 Tensor를 각각 더하고(+), 빼고(-), 곱하고(*), 나누세요(/).

In [4]:
# 여기에 코드를 작성합니다
a = torch.rand(3,3)
b = torch.rand(3,3)

answer_1 = torch.add(a,b)
answer_2 = torch.sub(a,b)
answer_3 = torch.mul(a,b) # a * b
answer_4 = torch.div(a,b) # a / b
print(answer_1)
print(answer_2)
print(answer_3)
print(answer_4)

tensor([[0.7126, 1.3678, 0.6612],
        [0.6859, 0.4402, 1.1294],
        [0.6834, 1.4126, 0.4945]])
tensor([[-0.1331,  0.1965,  0.6395],
        [ 0.0648, -0.1364,  0.3200],
        [ 0.2644,  0.3919, -0.1371]])
tensor([[0.1225, 0.4581, 0.0071],
        [0.1166, 0.0438, 0.2933],
        [0.0993, 0.4605, 0.0564]])
tensor([[ 0.6852,  1.3354, 59.9273],
        [ 1.2087,  0.5270,  1.7906],
        [ 2.2621,  1.7679,  0.5659]])


### 3. 행렬의 내적 연산
1. 2×3 크기의 Tensor A를 다음 값으로 생성하세요:
  - `[[1,2,3], [4,5,6]]`
2. 3×2 크기의 Tensor B를 다음 값으로 생성하세요:
  - `[[7,8],[9,10],[11,12]]`
3. 두 Tensor의 행렬 내적(행렬 곱) A×B를 계산하여 출력하세요.

In [24]:
# 여기에 코드를 작성합니다
tensor_a = torch.tensor([[1,2,3], [4,5,6]])
print(tensor_a)
tensor_b = torch.tensor([[7,8],[9,10],[11,12]])
print(tensor_b)
result = torch.matmul(tensor_a, tensor_b)
print(result)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]])
tensor([[ 58,  64],
        [139, 154]])


### 4. 행렬 연산과 값 제한
1. 이전 문제에서 계산된 행렬 R(결과 행렬 A×B)를 사용하세요
2. 행렬 R의 각 요소에 10을 더하세요.
3. R의 각 요소를 100보다 큰 값은 100으로, 나머지는 그대로 유지하도록 제한하세요.

In [25]:
# 여기에 코드를 작성합니다
result_add = result + 10
print(result_add)
answer = torch.clamp(result, max=100)
print(answer)

tensor([[ 68,  74],
        [149, 164]])
tensor([[ 58,  64],
        [100, 100]])


### 5. 행렬의 열별 합계 계산
1. 5×5 크기의 Tensor M을 다음 값으로 생성하세요
    ```
    [[1, 2, 3, 4, 5],
     [6, 7, 8, 9, 10],
     [11, 12, 13, 14, 15],
     [16, 17, 18, 19, 20],
     [21, 22, 23, 24, 25]]
    ```

2. 행렬 M의 각 열의 합계를 계산하세요.

In [27]:
# 여기에 코드를 작성합니다
tensor_m = torch.tensor([[1, 2, 3, 4, 5],
                        [6, 7, 8, 9, 10],
                        [11, 12, 13, 14, 15],
                        [16, 17, 18, 19, 20],
                        [21, 22, 23, 24, 25]
                        ])
print(tensor_m)
answer = torch.sum(tensor_m, dim=0)
print(answer)

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25]])
tensor([55, 60, 65, 70, 75])
