In [1]:
import torch
import numpy as np

## PyTorch Quiz 2 : 연산

### 1. 덧셈과 뺄셈 연습
1. [2, 4, 6]으로 초기화된 1D Tensor를 생성하세요.
2. 각 요소에 5를 더한 Tensor를 출력하세요.
3. 각 요소에서 3을 뺀 Tensor를 출력하세요.


In [18]:
tensor = torch.tensor([2,4,6])
tensor_1 = tensor + 5
tensor_2 = tensor - 3

print(tensor)
print(tensor_1)
print(tensor_2)

tensor([2, 4, 6])
tensor([ 7,  9, 11])
tensor([-1,  1,  3])


### 2. Tensor 간의 연산
1. 3x3 크기의 Tensor 2개를 생성하세요.
2. 두 Tensor를 각각 더하고(+), 빼고(-), 곱하고(*), 나누세요(/).

In [19]:
tensor_1 = torch.rand(3,3)
tensor_2 = torch.rand(3,3)

add = torch.add(tensor_1, tensor_2)
sub = torch.sub(tensor_1, tensor_2)
mul = torch.mul(tensor_1, tensor_2)
div = torch.div(tensor_1, tensor_2)

print(add)
print(sub)
print(mul)
print(div)




tensor([[1.3966, 1.0427, 0.6758],
        [0.7867, 0.8985, 1.7419],
        [0.4456, 0.7034, 1.5284]])
tensor([[-0.0858,  0.5889, -0.5637],
        [-0.5675, -0.2583,  0.0650],
        [-0.2992,  0.2501,  0.4482]])
tensor([[0.4858, 0.1851, 0.0348],
        [0.0742, 0.1851, 0.7575],
        [0.0273, 0.1081, 0.5338]])
tensor([[0.8842, 3.5957, 0.0905],
        [0.1619, 0.5534, 1.0776],
        [0.1965, 2.1036, 1.8299]])


### 3. 행렬의 내적 연산
1. 2×3 크기의 Tensor A를 다음 값으로 생성하세요:
  - `[[1,2,3], [4,5,6]]`
2. 3×2 크기의 Tensor B를 다음 값으로 생성하세요:
  - `[[7,8],[9,10],[11,12]]`
3. 두 Tensor의 행렬 내적(행렬 곱) A×B를 계산하여 출력하세요.

In [20]:
Tensor_A = torch.tensor([[1,2,3],[4,5,6]])
print(Tensor_A)
Tensor_B = torch.tensor([[7,8],[9,10],[11,12]])
print(Tensor_B)

mat = torch.matmul(Tensor_A,Tensor_B)
print(mat)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]])
tensor([[ 58,  64],
        [139, 154]])


### 4. 행렬 연산과 값 제한
1. 이전 문제에서 계산된 행렬 R(결과 행렬 A×B)를 사용하세요
2. 행렬 R의 각 요소에 10을 더하세요.
3. R의 각 요소를 100보다 큰 값은 100으로, 나머지는 그대로 유지하도록 제한하세요.

In [29]:
result = mat + 10
answer = torch.clamp(result, max = 100)

print(result)
print(answer)

tensor([[ 68,  74],
        [149, 164]])
tensor([[ 68,  74],
        [100, 100]])


### 5. 행렬의 열별 합계 계산
1. 5×5 크기의 Tensor M을 다음 값으로 생성하세요
    ```
    [[1, 2, 3, 4, 5],
     [6, 7, 8, 9, 10],
     [11, 12, 13, 14, 15],
     [16, 17, 18, 19, 20],
     [21, 22, 23, 24, 25]]
    ```

2. 행렬 M의 각 열의 합계를 계산하세요.

In [31]:
tensor = torch.tensor([[1, 2, 3, 4, 5],
     [6, 7, 8, 9, 10],
     [11, 12, 13, 14, 15],
     [16, 17, 18, 19, 20],
     [21, 22, 23, 24, 25]])
print (tensor)

answer = torch.sum(tensor, dim = 0)
print(answer)

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25]])
tensor([55, 60, 65, 70, 75])
